---
language: python
python: '3.6'
services:
  - postgresql

env:
  - GALAXY_DB_USER=postgres

cache:
  pip: true
  directories:
    - $HOME/.cache/pipenv

install:
  - pip install tox

jobs:
  include:
    - name: "Linters"
      script: tox -e linters

    - name: "Unit tests"
      script: tox -e py36
      services:
        - docker
        - postgresql
