# Generated by Django 2.2.4 on 2019-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='resources',
            field=models.TextField(blank=True),
        ),
    ]
