# Generated by Django 2.2.4 on 2019-09-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_api', '0002_namespace_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namespace',
            name='owners',
        ),
    ]
