# Generated by Django 2.2.4 on 2019-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_auth', '0002_replace_tenants_with_groups'),
        ('galaxy_api', '0003_remove_namespace_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='groups',
            field=models.ManyToManyField(related_name='namespaces', to='galaxy_auth.Group'),
        ),
    ]
